# Generated by Django 4.1.5 on 2023-01-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
        migrations.AddField(
            model_name='clothes',
            name='sex',
            field=models.CharField(choices=[('man', 'Hombre'), ('woman', 'Mujer'), ('unisex', 'Unisex')], default='unisex', max_length=6, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=123, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='stock',
            field=models.BooleanField(default=False, verbose_name='Existencias'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(max_length=123, verbose_name='Tipo de prenda'),
        ),
    ]
