# Generated by Django 4.1.5 on 2023-01-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_category_options_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Sin descripción', max_length=123, verbose_name='Descripción'),
        ),
    ]
