# Generated by Django 4.1.5 on 2023-01-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Prendas'},
        ),
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.CharField(choices=[('jumpers', 'Buzos'), ('shirts', 'Remeras'), ('caps', 'Gorras')], default='shirts', max_length=7, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(max_length=123, verbose_name='Prenda'),
        ),
    ]
