# Generated by Django 4.1.5 on 2023-01-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_category_options_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.CharField(choices=[('Buzos', 'Buzos'), ('Remeras', 'Remeras'), ('Gorras', 'Gorras')], default='shirts', max_length=7, verbose_name='Categoría'),
        ),
    ]
