# Generated by Django 4.1.5 on 2023-01-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=123, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='garment',
            field=models.CharField(max_length=123, verbose_name='Prenda'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Efectivo'), ('Card', 'Tarjeta')], max_length=4, verbose_name='Metodo de pago'),
        ),
    ]
